const data = {
  products: [
    {
      id: 1,
      category: ' Shirts',
      slug: 'item-1',
      img: 'images/shirt1.jpg',
      title: 'Item 1',
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 25,
      desc: ' Them item from ecom site',
      price: 50,
    },
    {
      id: 2,
      category: ' Shirts',
      slug: 'item-2',
      img: 'images/shirt2.jpg',
      title: 'Item 2',
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 25,
      desc: ' Them item from ecom site',
      price: 50,
    },
    {
      id: 3,
      category: ' Shirts',
      slug: 'item-3',
      img: 'images/shirt3.jpg',
      title: 'Item 3',
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 25,
      desc: ' Them item from ecom site',
      price: 50,
    },
    {
      id: 4,
      category: 'Shirts',
      slug: 'item-4',
      img: 'images/shirt4.jpg',
      title: 'Item 4',
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 25,
      desc: ' them item from ecom site',
      price: 50,
    },
    {
      id: 5,
      category: 'Shirts',
      slug: 'item-5',
      img: '/images/shirt5.jpg',
      title: 'Item 5',
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 25,
      desc: ' them item from ecom site',
      price: 50,
    },
    {
      id: 6,
      category: 'Shirts',
      slug: 'item-6',
      img: '/images/shirt6.jpg',
      title: 'Item 6',
      brand: 'Addidas',
      rating: 4.5,
      numReviews: 10,
      countInStock: 25,
      desc: ' themn item from ecom site',
      price: 50,
    },
  ],
};

export default data;
